version: '2.1'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - cas_db:/var/lib/cas_backup
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  auth:
    build: cas/
    ports:
      - "3012:3012"
    depends_on:
      db:
        condition: service_healthy

volumes:
  cas_db:
