source "http://rubygems.org"
gemspec

# OLD RUBY WHY
gem "nokogiri", "~> 1.3.3"
gem "rack-test", "~> 0.5.4"

# Adapter
gem 'mysql2', '0.3.11'

# Gems for authenticators
group :ldap do
    gem "net-ldap", "~> 0.1.1"
end

group :active_resource do
  gem "activeresource", ">= 2.3.12", "< 4.0"
end
